### PR TITLE
add contrib/metainfo with metainfo xml and screenshots

### PR DESCRIPTION
**Pull request by zebra-lucky**
add:
contrib/metainfo/org.dash.electrum.electrum_dash.metainfo.xml
contrib/metainfo/qt_history_list.png
contrib/metainfo/qt_send_tab.png

### CODE REVIEW

**Comment by zebra-lucky** [comment]
qt_history_list
qt_send_tab

**Comment by taw00** [comment]
Hmm.... dash-electrum.appdata.xml isn't sufficient? (Or org.dash.dash-electrum.appdata.xml  if you want or whatever.) The metainfo.xml file is for add-on packages. It doesn't really "add on" to some other existing application. I think the appdata.xml file should be enough.

Or am I being dense?

**Comment by zebra-lucky** [comment]
It's planned to be included in the next release buidl.
Added for memorize, if you can enhance I'll be thankfull.

**Comment by zebra-lucky** [comment]
path lenght is limsitd, but memory simmilar)

**Comment by taw00** [comment]
I don't think you understand. Or I don't understand you. There are two xml files used for desktop applications on linux:
1. name.appdata.xml
2. name.metainfo.xml

All desktops need #1. The second file is for applications that augment another application installed on the desktop. At least that is how I understand it.
https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/

**Comment by zebra-lucky** [comment]
Thanks for clarification, will remain it.

**Comment by zebra-lucky** [comment]
make some changes, it's more correct?

**Comment by taw00** [comment]
@zebra-lucky Yes, the filename suffix is now correct (appdata.xml).

@akhavr The question I have for you is the "dash electrum" and "electrum dash" thing. What's the "official name" of this project? If "dash electrum" perhaps the name of this appdata.xml file should be `org.dash.dash-electrum.appdata.xml` If the name is officially "electrum dash" then maybe `org.dash.electrum-dash.appdata.xml`?

My suspicion is that it should really be the former—`org.dash.dash-electrum.appdata.xml`—but I am not sure. I'm sorry if I am nit-picking this, but these things tend to linger forever, right or wrong. :)

**Comment by zebra-lucky** [comment]
For a notion, there is android builds, where hyphen is not correct in the package name.

https://stackoverflow.com/questions/10954030/valid-name-for-android-package-name?lq=1

**Comment by akhavr** [comment]
@taw00 official name is now Dash Electrum.  User visible name is also "Dash Electrum".  I'm not sure how useful would be at this point to change file names

**Comment by zebra-lucky** [comment]
@taw00, I will reading more docs. On flatpak app id, it was copied from android app, `org.dash.electrum.electrum_dash`, where `org.dash.electrum` full domain name.
`electrum_dash` is a legacy package name, where hyphen is not allowed.

So І choose this naming for app id. And it already set as app id in flatpak.
But app name is ```<name>Dash Electrum</name>```

For Fedora maybe need to make some simlink?

**Comment by zebra-lucky** [comment]
Upd: I was confused by docs from the link above:
https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/

But then re-reading this (on AppStream docs):
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location

Possibly can make `contrib/appdata` for Fedora Project with simlink named appropriately,
and return back previous commit with `contrib/metainfo`

**Comment by zebra-lucky** [comment]
Upd2: but `appdata.xml` file was processed with `appstream-util` to updgrade to metainfo spec,
then renamed to `metainfo.xml`.

And possibliy it is not conformed with `appdata.xml` after upgrade, need to be checked additionally.

**Comment by zebra-lucky** [comment]
For the file name, possibly it is not so principal, if `app id` and `app name` setup correctly.

**Comment by taw00** [comment]
All so confusing. :)

**Comment by zebra-lucky** [comment]
@taw00
I've intially created app_id.appdata.xml file (based on electrum app on flathub), then on request from flathub (on newly added apps) processed it with appstream-util and renamed to metainfo. Seems some standard changes.

**Pull request merged**
