### PR TITLE
fix ecc_fast.py for win64

### PR DESCRIPTION
**Pull request by zebra-lucky**
- fix ecc_fast.py for win64

### CODE REVIEW

**Comment by well0nez** [comment]
Iam using Windows 10 and the Dash Electrum Client,
I cannot send dash.

When i click the "send" button, the message appears:

"argument 1: <class 'OverflowError'>: int too long to convert"

**Comment by zebra-lucky** [comment]
> Iam using Windows 10 and the Dash Electrum Client,
> I cannot send dash.

Hi!

The problem should be fixed in 3.2.2.1 release:
https://github.com/akhavr/electrum-dash/releases/tag/3.2.2.1

**Comment by well0nez** [comment]
no its not

**Comment by well0nez** [comment]
well, the installer is not working for me.
nothing happens when i try to run it

**Comment by zebra-lucky** [comment]
Can you post version of windows you use?
These commands show detailed info:
```
ver
```
```
wmic os get osarchitecture
```

**Comment by akhavr** [comment]
@well0nez , please, open a separate issue for your problem and provide more info. as asked by @zebra-lucky.  Say, a screenshot of "nothing happens" would also help.

**Comment by chknlegz** [comment]
argument 1: <class 'OverflowError'>: int too long to convert
Happening on version 3.2.2 RC2 of the Electrum Vertcoin wallet.  Is there a fix for this? I am seeing above that this may have been fixed through this version but not happening for me.  Please advise.

**Comment by zebra-lucky** [comment]
It was fixed after 3.2.2.1.

**Comment by zebra-lucky** [comment]
Sorry, not Vertcoin, for Vrcoin you need to apply patch maybe.

**Comment by chknlegz** [comment]
I am having issues locating the link for the patch. could you direct me to this please?

**Comment by zebra-lucky** [comment]
https://github.com/akhavr/electrum-dash/pull/42/commits/a141b08489263b056db5b82819729ae2d44a2760

**Pull request merged**
