### PR TITLE
PS: add gathering mixing statistics

### LINKED ISSUE #264: Add optional mixing statistic
During mixing we get too many MN timeouts like

```
06/07/2021 10:04:03 PM Error in denominate worfklow: Session Timeout, Reset, workflow: 20d68761
```

Their amount don't seem to change significantly when increasing connection timeout, even way beyond [15 sec, used in Dash Core](https://github.com/dashpay/dash/blob/eaca69b22c5a5b1ec0a01e003c2d487542062b44/src/coinjoin/coinjoin-client.h#L30)

To help investigate this, create counters for

* total connections
* successful `send_dsa` reply
* successful `send_dsi` reply
* successful `send_dss` reply

More info re [p2p network privatesend messages](https://dashcore.readme.io/docs/core-ref-p2p-network-privatesend-messages)

### PR DESCRIPTION
**Pull request by zebra-lucky**
- dash_ps/qt/kivy: add gather_mix_stat option
- dash_ps_util.py: add DSMsgStat, MixingStats util classes
- dash_ps: gather stat info and show in info tab
- add test_MixingStats_DSMsgStat, test_gather_mix_stat

Fixes #264

### CODE REVIEW

**Comment by akhavr** [comment]
Though the code seems to update the content of `Info` tab on-the-fly, in reality this doesn't happen.  Have to switch from `Info` tab to other and back again..

**Comment by akhavr** [comment]
Ok, I was wrong.  Updates, but not immediately

**Comment by zebra-lucky** [comment]
Values are refreshed during all collateral flow:

for example for `dsa`
> dsa: all=253, ok=80, err=10, timeout=159, closed=0, dssu=242, ok min/max=0.2/25.6 sec
all: sent dsa messages
ok: read dsq with `fReady` set
err: some error rised
timeout: waiting message from peer timeout
closed: session closed by peer
ok min/max: min/max seconds for dsq with `fReady` set

**Comment by akhavr** [comment]
When user stops PS, and then starts again, stats is not reset.

**Comment by zebra-lucky** [comment]
Thinking to add Popup menu on Info view to clear stat (only when mixing stopped).

**Comment by zebra-lucky** [comment]
Added cleanup of statistics on toggle of "Gather mixing sessions statistics" option.
Change option help text to "Gather mixing sessions statistics (Reset on toggle)"

**Review by jardev — APPROVED** [review]
LGTM

**Pull request merged**
