### PR TITLE
Add dash network, refactor protx support, add InstantSend support

### PR DESCRIPTION
**Pull request by zebra-lucky**
* add DashNetwork for support (dash_net, dash_peer, dash_msg modules, qt/kivy gui)
* refactor ProTx support (stores ProTX MNs and LLMQ lists in file)
* add InstantSend support (wallet/stdio/text/qt/kivy)

### CODE REVIEW

**Comment by jardev** [comment]
In dash_msg.py, `('split').split()`, 'split'.split() - are all basically the same.

**Comment by jardev** [comment]
Magic numbers at https://github.com/akhavr/electrum-dash/pull/90/files#diff-3260ec5224f7b48b41b371d4fa061a6dR840 (e.g. `nHashFuncs > 50`, `blockHash`, etc)

**Comment by jardev** [comment]
Masternodes windows won't work. Fresh installation without anything else, just pip install and run, got:
```
(dash) ~/P/electrum-dash » ./electrum-dash                                                                                                                                                  add_dash_network ✗
Traceback (most recent call last):
  File "/home/risus/Projects/electrum-dash/electrum_dash/gui/qt/main_window.py", line 3464, in show_masternode_dialog
    d = MasternodeDialog(self.masternode_manager, self)
  File "/home/risus/Projects/electrum-dash/electrum_dash/gui/qt/masternode_dialog.py", line 294, in __init__
    manager.subscribe_to_network_updates()
AttributeError: 'MasternodeManager' object has no attribute 'subscribe_to_network_updates'
[1]    6321 abort (core dumped)  ./electrum-dash
```

**Comment by zebra-lucky** [comment]
- removed stale `subscribe_to_network_updates` method
- remove excess parentheses
- added msg limit vars

**Pull request merged**
